### ISSUE TITLE
parse fail - Unhandled exception. System.Collections.Generic.KeyNotFoundException - .sqlproj database project

### ISSUE THREAD

**Issue by timabell** [timabell/sln-items-sync#13]
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException:
The given key '00d1a9c2-b5f0-4af3-8072-f6c62b433612' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SlnEditor.Parsers.ProjectDefinitionParser.Parse(String line, Int32 lineNumber)
   at SlnEditor.Parsers.EnrichSolutionWithProjects.ParseFlatProjectList(IEnumerable`1 fileContents, Boolean bestEffort)
   at SlnEditor.Parsers.EnrichSolutionWithProjects.Enrich(Solution solution, IList`1 fileContents, Boolean bestEffort)
   at SlnEditor.Parsers.SolutionParser.ParseInto(String content, Solution solution)
   at SlnEditor.Models.Solution..ctor(String contents, Boolean bestEffort)
   at sln_items_sync.CLI.SyncSlnText(String contents, String slnFolder, IEnumerable`1 paths) in C:\dev\tim\sln-items-sync\src\CLI.cs:line 55
   at sln_items_sync.CLI.SyncSlnFile(String slnPath, String slnFolder, IEnumerable`1 paths) in C:\dev\tim\sln-items-sync\src\CLI.cs:line 48
   at sln_items_sync.CLI.<Run>b__4_0(Options opts) in C:\dev\tim\sln-items-sync\src\CLI.cs:line 33
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at sln_items_sync.CLI.Run(String[] args) in C:\dev\tim\sln-items-sync\src\CLI.cs:line 32
   at Program.<Main>$(String[] args) in C:\dev\tim\sln-items-sync\src\Program.cs:line 1
```

SSDT https://vsixcommunity.github.io/Community.VisualStudio.Toolkit/v1/api/EnvDTE.ProjectTypes.html#EnvDTE_ProjectTypes_SSDT

- Should fail with useful error.
- Should know about ssdt projects

**Comment by timabell** [comment]
fixed in https://www.nuget.org/packages/SlnEditor/6.1.0
